services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=phone_store'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
