version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=phone_store'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/phone_store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    links:
      - "db:db"
    ports:
      - "8080:8080"
    depends_on:
      - db